hook.Add("Initialize", "EMM.SetupEnv", function ()
	timer.Simple(0.25, function()
		RunConsoleCommand("sv_gravity", 300)
		RunConsoleCommand("sv_sticktoground", 0)
		RunConsoleCommand("sv_maxvelocity", 10000)
		RunConsoleCommand("sv_accelerate", 10)
		RunConsoleCommand("sv_airaccelerate", 10)
		RunConsoleCommand("sv_friction", 0)
	end)
end)
