GM.Name = "Parkour"
GM.Author = "arkade"

EMM.Include {
	"settings/settings",

	"util/variables",
	"util/util",
	"util/palette",
	"util/circles",
	"util/class",
	"util/cubic-bezier",
	"util/timer",
	"util/anim-value",
	"util/net",
	"util/pred-sound",
	"util/stamina",
	"util/time-associated-map",
	"util/unstuck",
	"util/savepoint",
	"util/spectate",
	"util/trail",
	"util/trigger",
	"util/tagging",
	"util/ghost",
	"util/sound-isolation",

	"player/hooks",
	"player/methods",
	"player-class/player-class",
	"player-class/net",
	"player-class/methods",

	"movement/walljump",
	"movement/wallslide",
	"movement/airaccel",
	"movement/autojump",
	"movement/airaccel-patch",
	"movement/slide",
	"movement/friction",
	"movement/gravity",

	"minigame/minigame",
	"minigame/prototype",
	"minigame/lobby",
	"minigame/hooks",
	"minigame/net",
	"minigame/states",
	"minigame/settings",
	"minigame/util",

	"element/element",
	"element/panel",
	"element/attributes",
	"element/setters",
	"element/layout",
	"element/stack",
	"element/paint",
	"element/states",

	"ui/variables",
	"ui/ui",
	"ui/util",
	"ui/cam",
	"ui/vardebug",
	"ui/elements/scroll-container",
	"ui/elements/text-bar",
	"ui/elements/button-bar",
	"ui/elements/meter-bar",
	"ui/elements/player-bar",
	"ui/elements/avatar-bar",
	"ui/elements/checkbox",
	"ui/elements/input-dragger",
	"ui/elements/text-input",
	"ui/elements/number-input",
	"ui/elements/time-input",
	"ui/elements/list-selector",
	"ui/elements/input-bar",

	"settings/ui",
	"settings/factories",

	"lobby-ui/lobby-ui",
	"lobby-ui/elements",
	"lobby-ui/factories",
	"lobby-ui/elements/lobby-bar",
	"lobby-ui/elements/lobby-card",
	"lobby-ui/elements/lobby-settings",

	"hud/variables",
	"hud/hud",
	"hud/elements",
	"hud/factories",
	"hud/nametags",
	"hud/indicators",
	"hud/notifications",
	"hud/elements/hud-meter",
	"hud/elements/crosshair-line",
	"hud/elements/crosshair-meter",
	"hud/elements/indicator",
	"hud/elements/notifications",
	"hud/elements/key-echo"
}
