GM.Name = "Extended Movement Mod"
GM.Author = "Jep Alaba"
GM.Email = "hello@jep.sh"
GM.Website = "jep.sh"

EMM.Include {
	"util/util",
	"util/palette",
	"util/class",
	"util/cubic-bezier",
	"util/anim-value",
	"util/net",
	"util/pred-sound",
	"util/stamina",
	"util/time-associated-map",
	"util/savepoint",
	"util/spectate",
	"util/trail",

	"player/hooks",
	"player/methods",
	"player-class/player-class",
	"player-class/net",
	"player-class/methods",

	"movement/walljump",
	"movement/wallslide",
	"movement/airaccel",
	"movement/autojump",
	"movement/airaccel-patch",
	"movement/slide",

	"minigame/minigame",
	"minigame/prototype",
	"minigame/lobby",
	"minigame/net",
	"minigame/states",
	"minigame/settings",
	"minigame/tagging",
	"minigame/util",

	"element/element",
	"element/panel",
	"element/attributes",
	"element/setters",
	"element/layout",
	"element/paint",
	"element/states",

	"ui/variables",
	"ui/ui",
	"ui/util",
	"ui/cam",
	"ui/vardebug",
	"ui/elements/text-bar",
	"ui/elements/button-bar",
	"ui/elements/meter-bar",
	"ui/elements/player-bar",
	"ui/elements/avatar-bar",
	"ui/elements/checkbox",
	"ui/elements/input-slider",
	"ui/elements/text-input",
	"ui/elements/time-input",
	"ui/elements/input-bar",

	"lobby-ui/variables",
	"lobby-ui/lobby-ui",
	"lobby-ui/elements",
	"lobby-ui/factories",
	"lobby-ui/elements/lobby-bar",
	"lobby-ui/elements/lobby-card",
	"lobby-ui/elements/lobby-settings",

	"hud/variables",
	"hud/hud",
	"hud/elements",
	"hud/factories",
	"hud/indicators",
	"hud/notifications",
	"hud/elements/meters",
	"hud/elements/crosshair-lines",
	"hud/elements/indicator",
	"hud/elements/notifications",
}
